### ISSUE TITLE
Add user with dropped password notification

### ISSUE THREAD

**Issue by benchdoos** [benchdoos/meetroom#8]
If user password was dropped, his profile badge must consist red block, informing that password was set to default and he must change password immediately.
On click he should be redirected to password change page (create it).
After password change, user must be marked as normal user, and he can login only with new password

**Comment by benchdoos** [comment]
Better send [email](https://www.baeldung.com/spring-email) to user. Or provide password setting url to admin if no email specified

**Comment by benchdoos** [comment]
On registration have problems:

```
2020-05-19T05:20:42.790574+00:00 app[web.1]:
2020-05-19T05:20:42.790575+00:00 app[web.1]: java.lang.IllegalStateException: No current ServletRequestAttributes
2020-05-19T05:20:42.790576+00:00 app[web.1]: at org.springframework.util.Assert.state(Assert.java:73) ~[spring-core-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
2020-05-19T05:20:42.790576+00:00 app[web.1]: at org.springframework.web.servlet.support.ServletUriComponentsBuilder.getCurrentRequest(ServletUriComponentsBuilder.java:179) ~[spring-webmvc-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
2020-05-19T05:20:42.790577+00:00 app[web.1]: at org.springframework.web.servlet.support.ServletUriComponentsBuilder.fromCurrentContextPath(ServletUriComponentsBuilder.java:147) ~[spring-webmvc-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
2020-05-19T05:20:42.790578+00:00 app[web.1]: at com.github.benchdoos.meetroom.config.beans.SpringConfigurationInfoBean.getPublicFullApplicationUrl(SpringConfigurationInfoBean.java:33) ~[classes!/:1.0]
2020-05-19T05:20:42.790579+00:00 app[web.1]: at com.github.benchdoos.meetroom.service.impl.GmailEmailServiceImpl.sendAccountActivation(GmailEmailServiceImpl.java:64) ~[classes!/:1.0]
2020-05-19T05:20:42.790580+00:00 app[web.1]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_252-heroku]
2020-05-19T05:20:42.790580+00:00 app[web.1]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_252-heroku]
2020-05-19T05:20:42.790581+00:00 app[web.1]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_252-heroku]
2020-05-19T05:20:42.790581+00:00 app[web.1]: at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_252-heroku]
2020-05-19T05:20:42.790582+00:00 app[web.1]: at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) ~[spring-aop-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
2020-05-19T05:20:42.790583+00:00 app[web.1]: at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
2020-05-19T05:20:42.790583+00:00 app[web.1]: at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
2020-05-19T05:20:42.790583+00:00 app[web.1]: at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[spring-aop-5.2.3.RELEASE.jar!/:5.2.3.RELEASE]
2020-05-19T05:20:42.790584+00:00 app[web.1]: at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_252-heroku]
2020-05-19T05:20:42.790584+00:00 app[web.1]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_252-heroku]
2020-05-19T05:20:42.790585+00:00 app[web.1]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_252-heroku]
2020-05-19T05:20:42.790585+00:00 app[web.1]: at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_252-heroku]
2020-05-19T05:20:42.790586+00:00 app[web.1]:
```

**Comment by benchdoos** [comment]
https://github.com/benchdoos/meetroom/issues/8#issuecomment-630588716
Fixed
